DROP DATABASE IF EXISTS todo_list;
CREATE DATABASE todo_list;

CREATE USER todo_user IDENTIFIED BY "todo_user";
GRANT ALL ON *.* TO todo_user WITH GRANT OPTION;

USE todo_list;

CREATE TABLE tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    description_ TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    
);